version: '2.1'
services:
  influxdb:
    image: influxdb:1.3
    volumes:
      - influx-data:/var/lib/influxdb
    logging:
      driver: syslog
    ports:
      - "8083:8083"
      - "8086:8086"
  mongodb:
    image: mongo:3.4
    volumes:
      - mongo-data:/data/db
    logging:
      driver: syslog
    ports:
      - "27017:27017"
    expose:
      - "27017"
  grafana:
    image: grafana/grafana:4.1.2
    volumes:
      - grafana-data:/var/lib/brood
    logging:
      driver: syslog
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    expose:
      - "3000"
    env_file:
      - grafana-variables-${ENV}.env
  vernemq:
    image: erlio/docker-vernemq:0.15.3
    volumes:
      - ./priv/ssl:/etc/ssl
    logging:
      driver: syslog
    ports:
      - "4883:4883"
    expose:
      - "4883"
    env_file:
      - vernemq-variables-${ENV}.env
  brood:
    build: .
    logging:
      driver: syslog
    depends_on:
      - vernemq
      - influxdb
      - mongodb
    env_file:
      - brood-${ENV}.env
    ports:
      - "4001:4001"
      - "443:443"
      - "80:80"


volumes:
  influx-data:
    driver: local
  grafana-data:
    driver: local
  mongo-data:
    driver: local
